### ISSUE TITLE
painless restart of everware

### ISSUE THREAD

**Issue by anaderi** [everware/everware#140]
if one fixes auth cookie for http_configurable_proxy , and saves `jupyterhub.sqlite` between start, user easily can connect to a running container , but as he clicks to 'Control Panel', he gets Error 500.
In log:

```
[E 2016-06-29 23:37:10.936 Everware web:1524] Uncaught exception GET /hub/home (84.201.150.25)
    HTTPServerRequest(protocol='http', host='everware.rep.school.yandex.net', method='GET', uri='/hub/home', version='HTTP/1.1', remote_ip='84.201.150.25', headers={'X-Forwarded-Proto': 'http', 'X-Nginx-Proxy': 'true', 'Accept-Language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'Accept-Encoding': 'gzip, deflate, br', 'X-Forwarded-For': '84.201.150.25,84.201.188.231', 'Host': 'everware.rep.school.yandex.net', 'Referer': 'https://everware.rep.school.yandex.net/user/anaderi/tree', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0', 'Connection': 'close', 'Cookie': 'jupyter-hub-token="2|1:0|10:1467231971|17:jupyter-hub-token|44:ZjNjODllNDZlNjIxNGQ1NzhhMTk1MTk5NTczY2JjYzE=|b1766e9f390c8176634d52fdaec7ee3438a6f98ee6612e270da18fefffb33d40"; yp=1467405426.gpauto.55_698586000000006%3A13_2014401%3A41%3A3%3A1467232626; ys=barff.8-19-1#vbff.2-27-1', 'X-Real-Ip': '84.201.150.25', 'X-Forwarded-Port': '80'})
    Traceback (most recent call last):
      File "/home/anaderi/miniconda3/envs/everware/lib/python3.5/site-packages/tornado/web.py", line 1445, in _execute
        result = yield result
      File "/home/anaderi/everware/everware/home_handler.py", line 55, in get
        branch_name = user.spawner.branch_name
      File "/home/anaderi/everware/everware/git_processor.py", line 118, in branch_name
        return self._branch_name
    AttributeError: 'CustomSwarmSpawner' object has no attribute '_branch_name'
```

**Comment by astiunov** [comment]
Was mentioned in #123. After server's restart all information about git repos is lost, so we should think how to store it. I propose to call `docker exec` and get all info from there in such cases.

**Comment by anaderi** [comment]
maybe store in sqlite? or would it require messing with jupyterhub source code?

**Comment by astiunov** [comment]
I discovered that Jupyterhub provides all we need to manipulate with spawner's state. Will make pr soon
