### ISSUE TITLE
unable to start everware if user's container is running since the last run of the everware

### ISSUE THREAD

**Issue by anaderi** [everware/everware#206]
scenario:
1. run everware
2. user logs in and runs container
3. stop everware, remove jupyterhub.sqlite
4. start everware again
it fails:

```
[D 2017-07-06 10:26:28.867 Everware spawner:458] Container baffc5f status: {'Dead': False,
     'Error': '',
     'ExitCode': 0,
     'FinishedAt': '0001-01-01T00:00:00Z',
     'OOMKilled': False,
     'Paused': False,
     'Pid': 444,
     'Restarting': False,
     'Running': True,
     'StartedAt': '2017-07-04T13:20:46.529610908Z',
     'Status': 'running'}
[E 2017-07-06 10:26:28.868 Everware app:1527]
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/app.py", line 1524, in launch_instance_async
        yield self.initialize(argv)
      File "/opt/conda/lib/python3.5/types.py", line 179, in throw
        return self.__wrapped.throw(tp, *rest)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/app.py", line 1315, in initialize
        yield self.init_spawners()
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/app.py", line 1087, in init_spawners
        status = yield spawner.poll()
      File "/srv/everware/everware/spawner.py", line 465, in poll
        yield wait_for_http_server(self.user.server.url, timeout=1)
    AttributeError: 'NoneType' object has no attribute 'url'

[D 2017-07-06 10:26:28.870 Everware application:642] Exiting application: everware
```

**Comment by anaderi** [comment]
workaround: remove all containers before starting everware again
